### ISSUE TITLE
Install doesn't work

### ISSUE THREAD

**Issue by ghost** [Danter14/LastTrav-T4#1]
I started install, filled out everything and i gor error: 
Fatal error: Cannot redeclare class MYSQL_DB in /home/domeceuj/public_html/evadercucc/t4/install/include/database.php on line 8

**Comment by ChefAharoni** [comment]
I have something like that too.

Fatal error: include() [<a href='function.include'>function.include</a>]: Cannot redeclare class mysqli_db in /data/multiserv/users/1114105/projects/2481919/www/install/process.php on line 70

**Comment by Danter14** [comment]
install MySQL
tested localhost = ok
Dédié = ok 
mutualiser = ok
