### ISSUE TITLE
I can't login to the game, but when I do my adress with 'www.mydomain.com/dorf1.php' it says this errors:

### ISSUE THREAD

**Issue by ChefAharoni** [Danter14/LastTrav-T4#3]
Warning: session_start() [function.session-start]: Cannot send session cookie - headers already sent by (output started at /data/multiserv/users/1114105/projects/2481643/www/dorf1.php:1) in /data/multiserv/users/1114105/projects/2481643/www/GameEngine/Session.php on line 49

Warning: session_start() [function.session-start]: Cannot send session cache limiter - headers already sent (output started at /data/multiserv/users/1114105/projects/2481643/www/dorf1.php:1) in /data/multiserv/users/1114105/projects/2481643/www/GameEngine/Session.php on line 49

Warning: Cannot modify header information - headers already sent by (output started at /data/multiserv/users/1114105/projects/2481643/www/dorf1.php:1) in /data/multiserv/users/1114105/projects/2481643/www/GameEngine/Session.php on line 177

Warning: mysql_fetch_array() expects parameter 1 to be resource, boolean given in /data/multiserv/users/1114105/projects/2481643/www/GameEngine/Database/db_MYSQL.php on line 594

Warning: mysql_fetch_assoc() expects parameter 1 to be resource, boolean given in /data/multiserv/users/1114105/projects/2481643/www/GameEngine/Database/db_MYSQL.php on line 661

Warning: mysql_fetch_array() expects parameter 1 to be resource, boolean given in /data/multiserv/users/1114105/projects/2481643/www/GameEngine/Database/db_MYSQL.php on line 678

Warning: mysql_fetch_array() expects parameter 1 to be resource, boolean given in /data/multiserv/users/1114105/projects/2481643/www/GameEngine/Database/db_MYSQL.php on line 497

Warning: mysql_fetch_array() expects parameter 1 to be resource, boolean given in /data/multiserv/users/1114105/projects/2481643/www/GameEngine/Database/db_MYSQL.php on line 594

Warning: mysql_fetch_assoc() expects parameter 1 to be resource, boolean given in /data/multiserv/users/1114105/projects/2481643/www/GameEngine/Database/db_MYSQL.php on line 2142

Warning: mysql_fetch_assoc() expects parameter 1 to be resource, boolean given in /data/multiserv/users/1114105/projects/2481643/www/GameEngine/Database/db_MYSQL.php on line 2118

Warning: mysql_fetch_array() expects parameter 1 to be resource, boolean given in /data/multiserv/users/1114105/projects/2481643/www/GameEngine/Database/db_MYSQL.php on line 2768

Warning: mysql_fetch_array() expects parameter 1 to be resource, boolean given in /data/multiserv/users/1114105/projects/2481643/www/GameEngine/Database/db_MYSQL.php on line 2780

Warning: mysql_fetch_array() expects parameter 1 to be resource, boolean given in /data/multiserv/users/1114105/projects/2481643/www/GameEngine/Database/db_MYSQL.php on line 2780

Warning: mysql_fetch_array() expects parameter 1 to be resource, boolean given in /data/multiserv/users/1114105/projects/2481643/www/GameEngine/Database/db_MYSQL.php on line 3285

Warning: mysql_fetch_array() expects parameter 1 to be resource, boolean given in /data/multiserv/users/1114105/projects/2481643/www/GameEngine/Database/db_MYSQL.php on line 594

Warning: mysql_fetch_assoc() expects parameter 1 to be resource, boolean given in /data/multiserv/users/1114105/projects/2481643/www/GameEngine/Database/db_MYSQL.php on line 661

Warning: mysql_fetch_array() expects parameter 1 to be resource, boolean given in /data/multiserv/users/1114105/projects/2481643/www/GameEngine/Database/db_MYSQL.php on line 678

Warning: mysql_fetch_array() expects parameter 1 to be resource, boolean given in /data/multiserv/users/1114105/projects/2481643/www/GameEngine/Database/db_MYSQL.php on line 497

Warning: mysql_fetch_array() expects parameter 1 to be resource, boolean given in /data/multiserv/users/1114105/projects/2481643/www/GameEngine/Database/db_MYSQL.php on line 594

Warning: mysql_fetch_assoc() expects parameter 1 to be resource, boolean given in /data/multiserv/users/1114105/projects/2481643/www/GameEngine/Database/db_MYSQL.php on line 2142

Warning: mysql_fetch_assoc() expects parameter 1 to be resource, boolean given in /data/multiserv/users/1114105/projects/2481643/www/GameEngine/Database/db_MYSQL.php on line 2118

Warning: Invalid argument supplied for foreach() in /data/multiserv/users/1114105/projects/2481643/www/GameEngine/Building.php on line 21

**Comment by burakbir** [comment]
i have almost the same thing first of all i have my gameengine and install folder set to file permission  777 during the installation everything is ok till the affter the multihunter password after i save the password for multihunter and press next it goes white and dose not move on to oasis how ever i have found a work around for this 

if you look at the istallation link befor you get to this point it has some thing like /index.php?=3   well what i did was just copy this link and when i get to the white screen i past this link and change the number to 4 or 5 depending on if it is on oasis or multihunter i get this error now once i finish the installation i go to the home page (keep in mind delete the index.HTML from your server so you are left with index.PHP) and login i type my account information and press enter my browser refreshes but it loads the logon page again i figered if AFTER i had tryed to log in if i changed the /login.php to /dorf1.php it takes me to my account where everything seems to work fine 

i have examined the log on ph and have not found any errors yet. if any one finds a fix please let me know 

P.S this is tied on MAMP Pro and on an online payed host

**Comment by burakbir** [comment]
hay again i did a bit of reading in to your error and it seems like you did not gave your file permissions set to 777 on the install folder or the GameEngine folder try deleting your database from your MySQL and making a new one that is fresh and reinstall the server but bake sure you have your fail permissions set to 777 instead of 755 

hope this helps :D

**Comment by ChefAharoni** [comment]
Now uploadnig again the files after you fixed some bugs.
Will check it in 30 min again if it works.

**Comment by ChefAharoni** [comment]
Well, It didn't helped..

**Comment by burakbir** [comment]
try to use a different host or make a dedicated server as travail t4 dose not work on most free hosts i have one that works i have tryed 000webhost ( google it ) i also have a dedicated server running this script message me if you would like the link

**Comment by ChefAharoni** [comment]
When I use 000webhost after a week-two they are blocking my host, saying its against their terms and rules.

**Comment by burakbir** [comment]
i have had my one there for about 3 weeks now and i got an email saying how is your website it seems to be attracting a lot of visitors.

also i have opened my own dedicated server yesterday you could try that out its tribes.com.nu

**Comment by ChefAharoni** [comment]
And its good? 
So should I open now at tribes or 000webhost ?

**Comment by burakbir** [comment]
http://tribes.com.nu is my server if you would like to play the game if you want to open a server you need a good host and at this moment 000webhost is the only one that will work as a free host and as long as you get more then 10 constant players the will not close your server

**Comment by ChefAharoni** [comment]
ohhh great, thanks.

**Comment by burakbir** [comment]
if and when you join let me know by messaging in game and i will send you some gold :) my in game name is admin

**Comment by ChefAharoni** [comment]
Thanks man.

**Comment by burakbir** [comment]
if you need help with installing your server on a free host i will gladly help message me personally and i will send you my skype name
