### ISSUE TITLE
Full screen map not loading up !

### ISSUE THREAD

**Issue by burakbir** [Danter14/LastTrav-T4#5]
hello again sorry if im being annoying or anything but i have one more question 

when i or my friends get a plus account and try to use full screen map is dose not load it sends me to http://localhost:8888/karte2.php?x=4&y=5 here and it dose not load any thing what is this problem ?

i have attached a screen shoot to show you 

![screen shot 2013-05-23 at 7 59 52 pm](https://f.cloud.github.com/assets/4460772/555901/b57c791e-c3ca-11e2-8356-a5a2c50b7c2c.png)

would be most appreciated if you could help

**Comment by Danter14** [comment]
thank you new fix
